apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/n18011/base-app.git
    targetRevision: HEAD
    path: k8s/overlays/dev/echo-service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
